=== HZsolt2024/ECCOX9WebXML_LEV/ECCOX9_0410/XMLSchemaEccox9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Etterem" type="etteremTipus" maxOccurs="unbounded"/>
                <xs:element name="Foszakacs" type="foszakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Szakacs" type="szakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Gyakornok" type="gyakornokTipus" maxOccurs="unbounded"/>
                <xs:element name="Vendeg" type="vendegTipus" maxOccurs="unbounded"/>
                <xs:element name="Rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!--Kulcsok-->
        <xs:key name="etterem_kulcs">
            <xs:selector xpath="Etterem"/>
            <xs:field xpath="@Ekod"/>
        </xs:key>
        
        <xs:key name="foszakalcs_kulcs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@Fkod"/>
        </xs:key>

        <xs:key name="gyakornok_kulcs">
            <xs:selector xpath="Gyakornok"/>
            <xs:field xpath="@GYkod"/>
        </xs:key>

        <xs:key name="vendeg_kulcs">
            <xs:selector xpath="Vendeg"/>
            <xs:field xpath="@Vkod"/>
        </xs:key>

        <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
            <xs:selector xpath="Rendeles"/>
            <xs:field xpath="@E_V_E"/>
        </xs:keyref>

        <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
            <xs:selector xpath="Rendeles"/>
            <xs:field xpath="@E_V_V"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@E_F"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
            <xs:selector xpath="Szakacs"/>
            <xs:field xpath="@E_SZ"/>
        </xs:keyref>

        <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
            <xs:selector xpath="Gyakornok"/>
            <xs:field xpath="@E_GY"/>
        </xs:keyref>


    <!--1:1 kapcsolathoz-->
        <xs:unique name="unique_foszakacs">
            <xs:selector xpath="Foszakacs"/>
            <xs:field xpath="@E_F"/>
        </xs:unique>
    </xs:element>

    <!--Komplex tipusok definiálása-->
    <xs:complexType name="etteremTipus">
        <xs:sequence>
        <xs:element name="Nev" type="xs:string"/>
        <xs:element name="Cim" type="cimTipus"/>
        <xs:element name="Csillag" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="Ekod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"/>
            <xs:element name="Utca" type="xs:string"/>
            <xs:element name ="Hazszam" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Fkod" type="xs:string" use="required"/>
        <xs:attribute name="E_F" type="xs:string" use="required"/> 
    </xs:complexType>

    <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="Reszleg" type="xs:string"/>
            <xs:element name="Nev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="SZkod" type="xs:string" use="required"/>
        <xs:attribute name="E_SZ" type="xs:string" use="required"/> 
    </xs:complexType>

    <xs:complexType name="gyakorlatTipus">
        <xs:sequence>
            <xs:element name="Kezdete" type="xs:string"/>
            <xs:element name="Idotartam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="gyakornokTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Gyakorlat" type="gyakorlatTipus"/>
            <xs:element name="Muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="GYkod" type="xs:string" use="required"/>
        <xs:attribute name="E_GY" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="vendegTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
            <xs:element name="Cim" type="cimTipus"/>
        </xs:sequence>
        <xs:attribute name="Vkod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="Osszeg" type="xs:integer"/>
            <xs:element name="Etel" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="E_V_E" type="xs:string" use="required"/>
        <xs:attribute name="E_V_V" type="xs:string" use="required"/>
    </xs:complexType>


</xs:schema>

=== HZsolt2024/ECCOX9WebXML_LEV/ECCOX9_0410/XMLeccox91.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaEccox9.xsd">
        
    <!--Ettermek-->
        
    <Etterem Ekod="e1">
                
        <Nev>Trofea</Nev>
                
        <Cim>
                        
            <Varos>Budapest</Varos>
                        
            <Utca>Visegradi</Utca>
                        
            <Hazszam>13</Hazszam>
                    
        </Cim>
                
        <Csillag>4</Csillag>
            
    </Etterem>
        
    <Etterem Ekod="e2">
                
        <Nev>Gundel</Nev>
                
        <Cim>
                        
            <Varos>Budapest</Varos>
                        
            <Utca>Gundel Károly</Utca>
                        
            <Hazszam>4</Hazszam>
                    
        </Cim>
                
        <Csillag>4</Csillag>
            
    </Etterem>
        
    <!--Foszakacs-->
        
    <Foszakacs E_F="e1" Fkod="f1">
                
        <Nev>Havas Péter</Nev>
                
        <Eletkor>35</Eletkor>
                
        <!--Vegzettsegek-->
                
        <Vegzettseg>Szakközépiskola</Vegzettseg>
                
        <Vegzettseg>Paul Bocuse Institue</Vegzettseg>
            
    </Foszakacs>
        
    <Foszakacs E_F="e2" Fkod="f2">
                
        <Nev>Nagy Károly</Nev>
                
        <Eletkor>30</Eletkor>
                
        <!--Vegzettsegek-->
                
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
            
    </Foszakacs>
        


    
    <!--Szakacsok-->
        
    <Szakacs E_SZ="e1" SZkod="sz1">
                
        <!-- Vegzettsegek-->
                
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
                
        <Vegzettseg>Szakközépiskola</Vegzettseg>
                
        <Vegzettseg>Paul Bocuse Institute</Vegzettseg>
                
        <Reszleg>Saucier</Reszleg>
                
        <Nev>Ötlet Elek</Nev>
            
    </Szakacs>
        
    <Szakacs E_SZ="e2" SZkod="sz2">
                
        <!-- Vegzettsegek-->
                
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
                
        <Vegzettseg>Szakközépiskola</Vegzettseg>
                
        <Reszleg>Entremetier</Reszleg>
                
        <Nev>Kocsis Tibor</Nev>
            
    </Szakacs>
        
    <Szakacs E_SZ="e2" SZkod="sz3">
                
        <!-- Vegzettsegek-->
                
        <Vegzettseg>Szakközépiskola</Vegzettseg>
                
        <Reszleg>Gardemanger</Reszleg>
                
        <Nev>Tálas Levente</Nev>
            
    </Szakacs>
        
    <Szakacs E_SZ="e2" SZkod="sz4">
                
        <!-- Vegzettsegek-->
                
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
                
        <Vegzettseg>Paul Bocuse Institute</Vegzettseg>
                
        <Reszleg>Entremetier</Reszleg>
                
        <Nev>Szűcs Judit</Nev>
            
    </Szakacs>
        
    <!--Gyakornokok-->
        
    <Gyakornok E_GY="e1" GYkod="gy1">
                
        <Nev>Bordas David</Nev>
                
        <Gyakorlat>
                        
            <Kezdete>2020.08.20.</Kezdete>
                        
            <Idotartam>2 hónap</Idotartam>
                    
        </Gyakorlat>
                
        <!--Muszakok-->
                
        <Muszak>Délelőtt</Muszak>
                
        <Muszak>Este</Muszak>
            
    </Gyakornok>
        
    <Gyakornok E_GY="e2" GYkod="gy2">
                
        <Nev>Szilágyi István</Nev>
                
        <Gyakorlat>
                        
            <Kezdete>2021.06.01.</Kezdete>
                        
            <Idotartam>4 hónap</Idotartam>
                    
        </Gyakorlat>
                
        <!--Muszakok-->
                
        <Muszak>Délután</Muszak>
            
    </Gyakornok>
        
    <Gyakornok E_GY="e1" GYkod="gy3">
                
        <Nev>Szentpétery Ferenc</Nev>
                
        <Gyakorlat>
                        
            <Kezdete>2021.01.01.</Kezdete>
                        
            <Idotartam>10 hónap</Idotartam>
                    
        </Gyakorlat>
                
        <!--Muszakok-->
                
        <Muszak>Délelőtt</Muszak>
                
        <Muszak>Délután</Muszak>
            
    </Gyakornok>
        
    <!--Vendegek-->
        
    <Vendeg Vkod="v1">
                
        <Nev>Fekete Péter</Nev>
                
        <Eletkor>21</Eletkor>
                
        <Cim>
                        
            <Varos>Miskolc</Varos>
                        
            <Utca>Márton</Utca>
                        
            <Hazszam>17</Hazszam>
                    
        </Cim>
            
    </Vendeg>
       
    
    <Vendeg Vkod="v2">
                
        <Nev>Bordás Áron</Nev>
                
        <Eletkor>25</Eletkor>
                
        <Cim>
                        
            <Varos>Eger</Varos>
                        
            <Utca>Dobó</Utca>
                        
            <Hazszam>12</Hazszam>
                    
        </Cim>
            
    </Vendeg>
        
    
    <Vendeg Vkod="v3">
                
        <Nev>Kiss Hajnalka</Nev>
                
        <Eletkor>26</Eletkor>
                
        <Cim>
                        
            <Varos>Miskolc</Varos>
                        
            <Utca>Egyetem-város</Utca>
                        
            <Hazszam>1</Hazszam>
                    
        </Cim>
            
    </Vendeg>
        
    <!--Rendelesek-->
        
    <Rendeles E_V_E="e1" E_V_V="v1">
                
        <Osszeg>9000</Osszeg>
                
        <Etel>Steak</Etel>
            
    </Rendeles>
        
    <Rendeles E_V_E="e2" E_V_V="v2">
                
        <Osszeg>8000</Osszeg>
                
        <Etel>Kaviár</Etel>
            
    </Rendeles>
        
    <Rendeles E_V_E="e1" E_V_V="v3">
                
        <Osszeg>20000</Osszeg>
                
        <Etel>Zsíros kenyér</Etel>
            
    </Rendeles>
        
    <Rendeles E_V_E="e2" E_V_V="v3">
                
        <Osszeg>300</Osszeg>
                
        <Etel>Mackó sajt</Etel>
            
    </Rendeles>
    
</vendeglatas>
